### ISSUE TITLE
Minimum VRAM Requirements for Running BioEMU

### ISSUE THREAD

**Issue by Verna929** [microsoft/bioemu#47]
Hi,

I was trying to run the test code. And no matter how I adjust, it always seems to pull out errors like this:

```
E0226 14:31:56.978591   20256 cuda_dnn.cc:534] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0226 14:31:56.978619   20256 cuda_dnn.cc:538] Memory usage: 7420444672 bytes free, 8223522816 bytes total.
E0226 14:31:56.978839   20256 cuda_dnn.cc:534] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0226 14:31:56.978854   20256 cuda_dnn.cc:538] Memory usage: 7420444672 bytes free, 8223522816 bytes total.
2025-02-26 14:31:56,982 Could not predict d8e91ab250bfed224e85e122cb2b35dde082a4054d8d62d05fffd0f9d10d4cd2__unknown_description_. Not Enough GPU memory? FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

```
It seems that my GPU is not powerful enough for running BioEMU. So I'm wondering what is the minimum VRAM requirement. And wondering are there any variables that we could change to make it run on small size GPUs? My current GPU is NVIDIA GeForce RTX 3070.

**Comment by josejimenezluna** [comment]
Hi @Verna929. The peak VRAM usage that I see running the example on the `README` is ~2GB. 

```
|   1  NVIDIA H100 NVL                Off |   00000000:02:00.0 Off |                    0 |
| N/A   41C    P0            305W /  400W |    2374MiB /  95830MiB |     98%      Default |
|                                         |                        |             Disabled |
```

Can you check with `nvidia-smi --query-gpu=memory.used --format=csv -i <gpu_id> -l 1`? Replace `<gpu_id>` with the GPU of interest.

**Comment by Verna929** [comment]
I ran the code you mentioned and found that the code was killed before being passed to the GPU.

This problem has been solved by manually source cuDNN every time before running anything.

```
export CUDNN_PATH=$(python -c "import nvidia.cudnn; print(nvidia.cudnn.__file__.replace('__init__.py', ''))")
export LD_LIBRARY_PATH=$CUDNN_PATH/lib:$LD_LIBRARY_PATH
```

Thanks for your help!
